Healthcheck and vulnerability updates
harvard-lts/listview pull request #19
Opened 2023-03-28 16:43 UTC by ives1227

**Healthchecks and vulnerability updates.**
* * *

**JIRA Ticket**: https://jira.huit.harvard.edu/browse/LTSMAINT-646

# What does this Pull Request do?
Adds healthcheck and updates vulnerable gems.  The Ruby (JRuby) was bumped as was the Rails version was bumped which required a number of config and code changes.

# How should this be tested?

Deployed to dev/qa.  Verify that dev/qa links work here: https://wiki.harvard.edu/confluence/pages/viewpage.action?spaceKey=LibraryTechServices&title=SysDev+-+ListView.
NOTE: QA DRS link is not currently working

# Test coverage
Yes/No: Are changes in this pull-request covered by:
- unit tests? no
- integration tests? no

2023-03-29 20:27 UTC, pobocks requested changes
A few questions that might or might not need action.

- The container appears to be running as root, I think we want to avoid this if possible?
- Psych reliably supports `aliases: true` now so the guard around it shouldn't be necessary.

2023-03-29 20:27 UTC, pobocks commented on Dockerfile
> +USER root
This image appears to be running as root - unless that's actively desired I think the last user statement ought to be 

```dockerfile
USER app
```

2023-03-29 20:27 UTC, pobocks commented on config/initializers/load_config.rb
> +  APP_CONFIG = YAML.load(ERB.new(File.read(Rails.root.join('config/config.yml'))).result, aliases: true)[Rails.env]
We're specifying the version of JRuby, and JRuby9.4 is equivalent to MRI 3.1, so Psych will reliably support `aliases: true` - you can take the begin/rescue out and remove the second alternative.

2023-03-30 14:32 UTC, ives1227 commented on config/initializers/load_config.rb
> +  APP_CONFIG = YAML.load(ERB.new(File.read(Rails.root.join('config/config.yml'))).result, aliases: true)[Rails.env]
Fixed

2023-04-03 19:42 UTC, pobocks requested changes

2023-04-03 19:42 UTC, pobocks commented on Dockerfile
> +USER root
Unless I'm reading this wrong, this still has `USER root` below `USER app`?  I think moving `USER app` to below line 63  would resolve this.

2023-04-03 19:42 UTC, pobocks commented on DockerfileLocal
> +RUN bundle install
This shouldn't afaik require root - does it (due to some passenger business) or is it a leftover?

2023-04-03 19:55 UTC, ives1227 commented on DockerfileLocal
> +RUN bundle install
Fixed the User root issue.  I think I lost the other user when I merged.

bundle install has a bunch of Jruby permission issues if I don't run it as root.  I can chmod or chown the directories but it seems to complain even when I do.  Root for that is OK.

2023-04-11 00:45 UTC, pobocks approved these changes

2023-04-11 00:45 UTC, merged